IMAGENES_EJERCICIOS = {
    "abdominal simple": "Abdominal.gif",
    "abdominal con rueda": "Abdominal_con_rueda.gif",
    "aperturas en maquina": "Aperturas_en_máquina.gif",
    "backhand cruzado": "Backhand_cruzado.gif",
    "backhand en movimiento": "Backhand_en_movimiento.gif",
    "bicicleta": "Bicicleta.gif",
    "bird dog": "Bird_dog.gif",
    "bote mano dominante": "Bote_a_una_mano.gif",
    "bote a una mano": "Bote_a_una_mano.gif",
    "bote explosivo": "Bote_explosivo.gif",
    "bote no dominante": "Bote_explosivo.gif",
    "cambios de dirección": "Cambios_de_dirección.gif",
    "cambios de ritmo": "Cambios_de_ritmo.gif",
    "caminadora": "Caminadora.gif",
    "conducción en zig zag": "Conducción_en_zig-zag.gif",
    "conducción recta": "Conduccion_recta.gif",
    "control orientado": "Control_orientado.gif",
    "core avanzado": "Core_avanzado.gif",
    "core en polea": "Core_en_polea.gif",
    "crol": "Crol.gif",
    "curl biceps alternado": "Curl_bíceps_alternado.gif",
    "curl femoral": "Curl_femoral.gif",
    "desplazamientos laterales": "Footwork_lateral.gif",
    "devolucion de servicio": "Devolución_de_servicio.gif",
    "drop shot": "Drop_shot.gif",
    "elevaciones frontales": "Elevaciones_frontales.gif",
    "elevaciones laterales": "Elevaciones_laterales.gif",
    "elevaciones de gemelos": "Elevaciones_de_gemelos.gif",
    "eliptica": "Elíptica_(cardio).gif",
    "espalda": "Espalda.gif",
    "entradas": "Entrada.gif",
    "estiramiento de cadera": "Estiramiento_de_cadera_(lunge_stretch).gif",
    "estiramiento de cuadriceps": "Estiramiento_de_cuádriceps.gif",
    "estiramiento de dorsales": "Estiramiento_de_dorsales.gif",
    "estiramiento de gemelos": "Estiramiento_de_gemelos.gif",
    "estiramiento de gluteo": "Estiramiento_de_glúteo_piriforme.gif",
    "estiramiento de isquiotibiales": "Estiramiento_de_isquiotibiales.gif",
    "estiramiento de pectorales": "Estiramiento_de_pectorales.gif",
    "estiramiento de triceps": "Estiramiento_de_tríceps.gif",
    "extension de triceps": "Extensión_de_tríceps.gif",
    "extensión cuádriceps": "Extension_de_cuadriceps.gif",
    "flotación dorsal": "Flotación_dorsal.gif",
    "flotación ventral": "Flotación_ventral.gif",
    "fondos en paralelas": "Fondos_en_paralelas.gif",
    "footwork lateral": "Footwork_lateral.gif",
    "forehand": "Forehand.gif",
    "giros defensivos": "Giros_defensivos.gif",
    "golpe en carrera": "Golpe_en_carrera.gif",
    "golpes de derecha en estático": "Forehand.gif",
    "desplazamientos con golpe de derecha": "Forehand.gif",
    "desplazamientos con revés": "Backhand_cruzado.gif",
    "golpes de revés en estático": "Backhand_cruzado.gif",
    "rally cruzado controlado": "Split_step.gif",
    "golpes con entrenador aleatorio": "Devolución_de_servicio.gif",
    "jalón al pecho": "Jalon_al_pecho.gif",
    "layups": "Layups.gif",
    "paradas en uno y dos tiempos": "Paradas_en_uno_y_dos_tiempos.gif",
    "pase": "Pase.gif",
    "patada con tabla": "Patada_de_crol_con_tabla.gif",
    "patada vertical": "Patada_vertical.gif",
    "patada lateral": "Patada_vertical.gif",
    "pecho": "Pecho.gif",
    "peso muerto": "Peso_muerto.gif",
    "plancha": "Plancha_frontal.gif",
    "plancha lateral": "Plancha_lateral.gif",
    "plank leg raises": "Plank_leg_raises.gif",
    "prensa de pierna": "Prensa_de_piernas.gif",
    "prensa": "Prensa_de_piernas.gif",
    "press militar": "Press_militar.gif",
    "press de pecho": "Press_de_pecho.gif",
    "pull-over con mancuerna": "Pullover.gif",
    "remo con barra": "Remo_con_barra.gif",
    "remo con mancuerna": "Remo_con_mancuerna.gif",
    "remo de pie cuerda": "Remo_cuerda.gif",
    "rotadores externos con banda": "Rotadores_externos_con_banda.gif",
    "rotadores con banda": "Rotadores_externos_con_banda.gif",
    "rotaciones con cable": "Rotadores_externos_con_banda.gif",
    "rotación explosiva": "Rotadores_externos_con_banda.gif",
    "rally": "Smash.gif",
    "juego de puntos": "Forehand.gif",
    "mini rally en media cancha": "Smash.gif",
    "servicio + primer golpe": "Drop_shot.gif",
    "remo sentado": "Remo_sentado.gif",
    "saltos verticales": "Saltos_al_cajon.gif",
    "sentadilla": "Sentadilla_guiada.gif",
    "servicios basicos": "Servicios_básicos.gif",
    "smash": "Smash.gif",
    "salidas explosivas": "Salida.gif",
    "split step": "Split_step.gif",
    "sprints": "Sprints_cortos.gif",
    "sprints cortos": "Sprints_cortos.gif",
    "superman": "Superman.gif",
    "respiración bilateral": "Técnica_de_respiración.gif",
    "tiros en movimiento": "Tiro_en_movimiento.gif",
    "tiros en suspensión": "Tiro_en_suspensión.gif",
    "trabajo de muñeca": "muñeca.gif",
    "tiros cortos": "Tiro_libre.gif",
    "tiros a portería": "Tiros_al_arco.gif",
    "trabajo de velocidad": "Trabajo_de_velocidad_(sprints).gif",
    "volea": "Volea.gif",
    "zig-zag entre conos": "Conducción_en_zig-zag.gif",
    "1 vs 1 suave": "1v1.gif",
    "virajes rápidos": "Viraje.gif",
    "partido reducido": "1v1.gif",
    "zancadas": "Zancada.gif"
}

GIF_POR_DEFECTO = "Superman.gif"
